selfedu/News/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.News, name='news_home'),
    path('create', views.Create, name='create'),
    path('<int:pk>', views.NewsDetailView.as_view(), name='news-detail')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

selfedu/ProducT/urls.py
from django.urls import path, include

from ProducT.views import (
    creation_view,
    main_view,
    # ProductsDetailView,
    detailed_view,
)

app_name = "product"

urlpatterns = [
    path('', main_view, name="main_view"),
    # path('<int:pk>', ProductsDetailView.as_view(), name="detailed_product"),
    path('/<int:pk>', detailed_view, name="detailed_product"),
    path('/create_product', creation_view, name="creation_view"),
    # path(r'^tinymce/', include('tinymce.urls')),
]

selfedu/account/urls.py
from django.urls import path

from account.views import (
    account_view,
    edit_account_view,
    crop_image,

)

app_name = "account"

urlpatterns = [
    path('<user_id>', account_view, name="view"),
    path('<user_id>/edit', edit_account_view, name="edit"),
    path('<user_id>/edit/cropImage', crop_image, name="crop_image"),
]

selfedu/basket/urls.py
from django.urls import path

from basket.views import (
    basket_summary,
    basket_add,
    basket_delete,
    basket_update,
)

app_name = 'basket'

urlpatterns = [
    path('', basket_summary, name='basket_summary'),
    path('add/', basket_add, name='basket_add'),
    path('delete/', basket_delete, name='basket_delete'),
    path('update/', basket_update, name='basket_update'),
]

selfedu/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.func, name='main'),
    path('test', views.test),
    path('about', views.Extention, name='about'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

selfedu/selfedu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,
)

# from products.views import (
#     creation_view,
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('fizmat/', include('fizmat.urls')),
    path('news/', include('News.urls')),

    path('register', register_view, name="register"),
    path('logout', logout_view, name="logout"),
    path('login', login_view, name="login"),
    path('account/', include('account.urls', namespace='account')),
    path('search/', account_search_view, name="search"),


    # path('products', include('products.urls', namespace='products')),
    path('products', include('ProducT.urls', namespace='products')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('tinymce/', include('tinymce.urls')),

    path('password_change', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_change'),
    path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

selfedu/main/models.py
from django.db import models

# Create your models here.

selfedu/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def func(request):
   return render(request, 'main/func.html')

def Extention(request):
   return render(request, 'main/SameHTML.html')

def test(request):
   return HttpResponse("<h4><font color=blue>QWERTY</font><h4>")

selfedu/main/templates/main/SameCode.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> {% block CSS %}{% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <title>{% block title %} {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'cropperjs/dist/cropper.min.css' %}">

</head>
<body>

<div class="container" id="id_loading_spinner" style="display: none;">
    <div class="d-flex flex-row mx-auto flex-grow-1 justify-content-center">
        <div class="spinner-border text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
</div>


<div class="banner">
    <aside class="Logo" style="width:145px; position: absolute;"><img src="{% static 'main/img/LogoN1.png' %}"
    style="width:130px; height:60px; margin-left:15px; margin-top:5px;" alt="Logo"></aside>
    <ul>
        <a href="{% url 'main' %}"><li><i class="fas fa-home"></i> Main </li></a>
        <a href="{% url 'about' %}"><li  style=""><i class="fas fa-info"></i> About us</li></a>
        <a href="{% url 'news_home' %}"><li style=""><i class="fas fa-newspaper"></i> News </li></a>
        <a href="{% url 'products:main_view' %}"><li style=""><i class="fas fa-graduation-cap"></i> Products </li></a>
<!--        <a href="{% url 'fizmat_home' %}"><li><i class="fas fa-atom"></i> Fizmat University </li></a>-->
    </ul>

    {% if request.user.is_authenticated %}
<!--    <form class="search-bar justify-content-start" onsubmit="return executeQuery();">-->
<!--			<input type="text" class="form-control" name="q" id="id_q_small" placeholder="Search users...">-->
<!--		</form>-->

<!--    <div class="dropdown dropleft show p-2" style="margin-left:90vw; margin-top:-40px">-->
<!--         <a type="button" role="button" href="{% url "basket:basket_summary" %}"-->

<!--                        class="btn btn-outline-secondary">-->
<!--                        {% with total_qty=basket|length %}-->
<!--                            <div id="basket-qty" class="d-inline-flex">-->
<!--                                {% if total_qty > 0 %}-->
<!--                                    {{ total_qty }}-->
<!--                                {% else %}-->
<!--                                    0-->
<!--                                {% endif %}-->
<!--                            </div>-->
<!--                        {% endwith %}-->

<!--                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"-->
<!--                            class="bi bi-cart3" viewBox="0 0 16 16">-->
<!--                            <path-->
<!--                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />-->
<!--                        </svg>-->
<!--                    </a>-->
<!--    </div>-->


    <div class="dropdown dropleft show p-2" style="margin-left:95vw; margin-top:-50px">
						<div class="d-flex flex-row">
                                <div class="btn-group dropleft">
								<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="user logo" width="40" height="40">
								<div class="dropdown-menu" aria-labelledby="id_profile_links">
									<a class="dropdown-item" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
									<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
								</div>
							</div>
						</div>

					</div>
    <div class="login" style="margin-left:80vw; margin-top:-40px">
        <a href="{% url 'account:view' user_id=request.user.id %}" style="color: black; text-decoration: none;">Account/</a>
        <a href="{% url 'logout' %}" style="color: black; text-decoration: none; margin-left:0px">Logout</a>
    </div>



<!--<div class="btn-group dropend">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Dropright
  </button>
  <ul class="dropdown-menu">
  </ul>
</div> -->

<!--        <a class="logout" href="{% url 'logout' %}"> Log Out</a>-->
<!--        <img class="account-logo" src="{{ request.user.profile_image }}">-->
<!--        <a class="user_profile" href="{% url 'account:view' user_id=request.user.id %}">Account</a>-->
    {% else %}
        <a class="register" href="{% url 'register' %}"> Register</a>
        <a class="login" href="{% url 'login' %}"> Log In</a>
    {% endif %}

<!--
    <div class="dropdown dropleft p-2 mt-2">
						<div class="btn-group dropleft">
							<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" width="20" height="20">
							<div class="dropdown-menu" aria-labelledby="id_profile_links">
								<a class="dropdown-item" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
								<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
							</div>
					    </div>
				</div>-->

    <h3>{% block h3 %}{% endblock %}</h3>

</div>

<main>
{% block body %}

{% endblock %}
</main>

<div class="bottom">
    <h6 style="margin-left:10px">Contacts:</h6>
    <a href="https://t.me/XelerLib" style="margin-bottom"> <button class="btn btn-link">Developer</button></a>
</div>

<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script type="module" src="{% static 'cropperjs/dist/cropper.min.js' %}"></script>




</body>
</html>

<script type="text/javascript">
	function executeQuery() {
		var query = document.getElementById('id_q_small').value;
		if (query == ""){
			query = document.getElementById('id_q_large').value;
		}
	    window.location.replace("{% url 'search' %}?q=" + query)
	    return false
	}

    function displayLoadingSpinner(isDisplayed){
        var spinner = document.getElementById("id_loading_spinner")
        if(isDisplayed){
            spinner.style.display = "block"
        }
        else{
            spinner.style.display = "none"
        }
    }

</script>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<script type="module" src="{% static 'cropperjs/dist/cropper.min.js' %}"></script>

selfedu/main/templates/main/SameHTML.html
{% extends 'main/SameCode.html' %}
{% load static %}
{% block CSS %}<link rel="stylesheet" href="{% static 'main/CSS/main.css' %}">{% endblock %}
{% block title %}
About Us
{% endblock %}


{% block body %}

<div class="features">

    <h1> About us </h1>
    <p></p>


</div>
{% endblock %}

selfedu/main/templates/main/func.html
{% extends 'main/SameCode.html' %}
{% load static %}
{% block CSS %}<link rel="stylesheet" href="{% static 'main/CSS/main.css' %}">{% endblock %}
{% block title %}

    Main page

{% endblock %}

{% block body %}

<div class="features">

    <h1> Main </h1>
    <p> </p>

</div>

{% endblock %}