selfedu/News/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.News, name='news_home'),
    path('create', views.Create, name='create'),
    path('<int:pk>', views.NewsDetailView.as_view(), name='news-detail')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

selfedu/ProducT/urls.py
from django.urls import path, include

from ProducT.views import (
    creation_view,
    main_view,
    # ProductsDetailView,
    detailed_view,
)

app_name = "product"

urlpatterns = [
    path('', main_view, name="main_view"),
    # path('<int:pk>', ProductsDetailView.as_view(), name="detailed_product"),
    path('/<int:pk>', detailed_view, name="detailed_product"),
    path('/create_product', creation_view, name="creation_view"),
    # path(r'^tinymce/', include('tinymce.urls')),
]

selfedu/basket/urls.py
from django.urls import path

from basket.views import (
    basket_summary,
    basket_add,
    basket_delete,
    basket_update,
)

app_name = 'basket'

urlpatterns = [
    path('', basket_summary, name='basket_summary'),
    path('add/', basket_add, name='basket_add'),
    path('delete/', basket_delete, name='basket_delete'),
    path('update/', basket_update, name='basket_update'),
]

selfedu/selfedu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,
)

# from products.views import (
#     creation_view,
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('fizmat/', include('fizmat.urls')),
    path('news/', include('News.urls')),

    path('register', register_view, name="register"),
    path('logout', logout_view, name="logout"),
    path('login', login_view, name="login"),
    path('account/', include('account.urls', namespace='account')),
    path('search/', account_search_view, name="search"),


    # path('products', include('products.urls', namespace='products')),
    path('products', include('ProducT.urls', namespace='products')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('tinymce/', include('tinymce.urls')),

    path('password_change', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_change'),
    path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

selfedu/ProducT/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from embed_video.fields import EmbedVideoField
from tinymce.models import HTMLField
from ckeditor.fields import RichTextField
# from tinymce.widgets import TinyMCE

class ProductManager():

    def create_product(self, product_name, product_descr):
        if not product_name:
            raise ValueError("Product must have name")
        if not product_descr:
            raise ValueError("Product must have a description")

        product = self.model(
            product_name=product_name,
            product_descr=product_descr,
        )
        product.save(using=self._db)
        return product


def get_product_image_filepath(self, filename):
    return f'product_image/{self.pk}/{product_image.png}'

def get_default_product_image():
    return "media_cdn/default_product.png"

def product_directory_path(self,filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'product_{0}/{1}'.format(self.id, filename)

class Product(models.Model):

    product_name    = models.CharField(max_length=100, unique=True)
    product_descr   = models.CharField(max_length=250)
    date_created    = models.DateTimeField(verbose_name="date created", auto_now_add=True)
    product_image   = models.ImageField(max_length=255, upload_to=get_product_image_filepath, null=True, blank=True, default=get_default_product_image)
    product_cost    = models.FloatField(default=0)
    product_type    = models.CharField(max_length=100)
    product_creator = models.CharField(max_length=50)
    product_video   = EmbedVideoField(default='https://www.youtube.com/watch?v=SlLIEU2e7BA')
    product_file    = models.FileField(upload_to=product_directory_path, null=True)
    content         = RichTextField()
    content_tiny    = models.TextField()


    def __str__(self):
        return self.product_name

selfedu/basket/models.py
from django.db import models

# Create your models here.

selfedu/ProducT/forms.py
from django import forms
from django.forms import ModelForm, TextInput, DateTimeInput
# from tinymce.widgets import TinyMCE

from ProducT.models import Product

class CreationForm(ModelForm):

    # product_name = forms.CharField(max_length=100, help_text="Required. Add a valid product name.")
    # content_math    = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    class Meta:
        model = Product
        fields = ('product_name', 'product_descr', 'product_type', 'product_video', 'product_file', 'product_creator', 'content', )

    def clean_product_name(self):
        product_name = self.cleaned_data['product_name']
        try:
            product = Product.objects.get(product_name=product_name)
        except Exception as e:
            return product_name
        raise forms.ValidationError(f"Name {product_name} is already in use.")

selfedu/ProducT/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from ProducT.forms import CreationForm
from ProducT.models import Product
from django.views.generic import DetailView

from django.shortcuts import render
from django.http import FileResponse, Http404

def creation_view(request):
    # product = request.product
    context = {}
    if request.POST:
        form = CreationForm(request.POST)
        if form.is_valid():
            form.save()
            destination = get_redirect_if_exists(request)
            if destination:
                return redirect(destination)
            return redirect('main_view')
        else:
            context['creation_form'] = form
    return render(request, 'ProducT/create.html', context)


def get_redirect_if_exists(request):
    redirect = None
    if request.GET:
        if request.GET.get("next"):
            redirect = str(request.GET.get("next"))
    return redirect

def main_view(request):
    Products = Product.objects.order_by('date_created')
    return render(request, 'ProducT/Products.html', {'Products': Products})


# def view_pdf(request, pk):
#     pdf = get_object_or_404(Product, pk=pk)
#     image_data = open(pdf.file.url, "rb").read()
#     return HttpResponse(image_data, contenttype='application/pdf')


def detailed_view(request, *args, **kwargs):
    context = {

    }
    product_id = kwargs.get("pk")
    try:
        product = Product.objects.get(pk=product_id)
    except Product.DoesNotExist:
        return HttpResponse("That product doesn't exist.")
    if product:
        context['id'] = product.id
        context['product_name'] = product.product_name
        context['description'] = product.product_descr
        context['product_image'] = product.product_image.url
        context['product_creator'] = product.product_creator
        context['product_cost'] = product.product_cost
        context['video'] = product.product_video
        context['file'] = product.product_file
        context['conspect'] = product.content
        context['content'] = product.content_tiny

    return render(request, 'ProducT/product.html', context)




# class ProductsDetailView(DetailView):
#     model = Product
#     template_name = 'ProducT/product.html'
#     context_object_name = 'ProducT'

selfedu/basket/views.py
from django.shortcuts import render

from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from ProducT.models import Product

from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'ProducT/basket.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('id'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('id'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

selfedu/ProducT/templates/ProducT/Products.html
{% extends 'main/SameCode.html'%}
{% load static %}
{% block CSS %}
<link rel="stylesheet" href="{% static 'News/CSS/News.css' %}" xmlns:text-decoration="http://www.w3.org/1999/xhtml">{% endblock %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
{%block title%} Products {%endblock%}

{%block body%}

<div class="features">

    <h1> Our Products</h1>
    <p> </p>

</div>

{% for el in Products %}
    <div class="News">
        <img src="{{el.product_image.url}}" alt="product logo" width="140" height="80">
        <a href="{% url 'products:detailed_product' el.id %}" style="text-decoration:none; color:black;"><h4>{{el.product_name}}</h4></a>
        <a href="{% url 'products:detailed_product' el.id %}" style="text-decoration:none; color:black;"><p>{{el.product_descr}}</p></a>
</div>
{% endfor %}

{% if request.user.is_admin %}
<div class="Panel">
    <a href="{% url 'products:creation_view' %}"> <i class="fas fa-pen"></i>New Product</a>
</div>
{% endif %}

{%endblock%}

selfedu/ProducT/templates/ProducT/basket.html
{% extends "main/SameCode.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block CSS %}<link rel="stylesheet" href="{% static 'News/CSS/News.css' %}">
{% endblock %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
{% block body %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping basket</h1>
    {% for item in basket %}
    {% with product=item.product %}
    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2">{{ product.title }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Hardback Book</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">£{{ product.price }}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>
                <select id="select{{product.id}}">
                  <option selected>
                    {{item.qty}}
                  </option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <button type="button" id="update-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm update-button">
                  Update
                </button>
                <button type="button" id="delete-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button">
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: £<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div></div>
    </div>
  </div>
</main>

<script>
  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data('index'),
        productqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}

selfedu/ProducT/templates/ProducT/create.html
{% extends 'main/SameCode.html' %}
{% load static %}
{% block CSS %}
<link rel="stylesheet" href="{% static 'main/CSS/main.css' %}" xmlns:text-decoration="http://www.w3.org/1999/xhtml">{% endblock %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
{%block title%} Create {%endblock%}

{%block body%}

<div class="features">

    <h1> Create new product </h1>
    <p> </p>

</div>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-signin">
		  <div class="card-body">
		    <form class="form-post" method="post">{% csrf_token %}
				<div class="d-flex flex-column pb-3">
				<img class="img-fluid mx-auto d-block" src="{% static 'main/img/LogoN1.png' %}">
				</div>
				<input type="text" name="product_name" id="inputEmail" class="form-control" placeholder="Product Name" required autofocus>

				<input type="text" name="product_descr" id="inputDescription" class="form-control" placeholder="Description" required>

				<input type="text" name="product_type" id="inputType" class="form-control" placeholder="Type" required>

				<input type="text" name="product_video" id="inputVideo" class="form-control" placeholder="Video">

				<input type="file" name="product_file" id="inputFile" class="form-control" placeholder="File">

				<input type="text" name="product_creator" id="inputCreator" class="form-control" placeholder="Creator" required>

<!--				<input type="text" name="content" id="inputConspect" class="form-control" placeholder="Conspect">-->


				{% for field in creation_form %}
				<p>
				{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if creation_form.non_field_errors %}
				<div style="color: red">
					<p>{{creation_form.non_field_errors}}</p>
				</div>

				{% endif %}

				<button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>

				</form>
		  </div>
		</div>

	</div>
</div>

{% endblock body %}

selfedu/ProducT/templates/ProducT/product.html
{% extends 'main/SameCode.html'%}
{% load static %}
{% load latexify %}
{% include "latexify/scripts.html" %}
<!--{% include 'latexify/stylesheets.html' %}-->
{% load embed_video_tags %}
{% block CSS %}<link rel="stylesheet" href="{% static 'News/CSS/News.css' %}">
{% endblock %}
<!--<script src="https://cdn.tiny.cloud/1/21qyk0dzoshxmq6hbubacdrtdl8jomw0wreg17slzaezkiks/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- <script>-->
<!--      tinymce.init({-->
<!--         selector: 'textarea#full-featured',-->
<!--      });-->
<!--    </script>-->
{%block title%} Products {%endblock%}

{%block body%}

<div class="title">

    <h1> {{product_name}} </h1>

</div>

<div class="text">

    <h4>{{description}}</h4>

<!--    <div>-->
<!--    <div class="col-6 text-end"><span class="h4 fw-bold">${{ product_cost }}</span></div>-->
<!--<button type="button" id="add-button" value="{{id}}" class="btn btn-secondary btn-sm">Добавить в корзину</button></div>-->

<!--</div>-->




<div class="Date">

    <h5>{{product_creator}}</h5>

</div>

<div class="lessons" style="margin:15vh">
<!--    {% video video 'medium' %}-->
    <div class="conspect" style="position:center; margin-top: 5vh">
<!--        {{ conspect | safe }}-->

       {{content | safe}}

    </div>
</div>


<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                id: $('#add-button').val(),
                productqty: "1",
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{%endblock%}